#!/usr/bin/env node
/**
 * Build script for Sticky Notes Chrome Extension v2.0.0
 * Bundles ES modules into a single contentScript.js for Chrome MV3 compatibility.
 * 
 * Chrome MV3 content_scripts don't support ES module imports,
 * so we inline all modules into a single IIFE bundle.
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const ROOT = __dirname;
const BUILD_DIR = path.join(ROOT, 'build');
const TEMP_DIR = path.join(ROOT, 'temp_zip_dir');

// Module load order (dependency order — config first, then dependents)
const MODULES = ['config', 'storage', 'drag', 'features', 'dashboard', 'ui', 'keyboard', 'richtext', 'darkmode', 'markdown', 'error', 'sanitizer'];

function bundleContentScript() {
  console.log('🔨 Bundling ES modules into contentScript.js...\n');

  const parts = [];
  parts.push(`// Sticky Notes Extension - v2.0.0 (Bundled)
// Auto-generated by build.js — do not edit manually
// All modules inlined for Chrome MV3 compatibility

(function() {
'use strict';

`);

  // Inline each module, converting exports to top-level declarations in the IIFE scope
  for (const modName of MODULES) {
    const modPath = path.join(ROOT, 'modules', `${modName}.js`);
    let code = fs.readFileSync(modPath, 'utf8');

    // Remove import lines (all modules are in same scope now)
    code = code.replace(/^import\s+.*?;\s*$/gm, '');

    // Convert `export const` → `const`
    code = code.replace(/^export\s+const\s+/gm, 'const ');

    // Convert `export let` → `let`
    code = code.replace(/^export\s+let\s+/gm, 'let ');

    // Convert `export (async) function` → `(async) function`
    code = code.replace(/^export\s+(async\s+)?function\s+/gm, (match, async_) => {
      return async_ ? 'async function ' : 'function ';
    });

    // Convert `export default function` → `function`
    code = code.replace(/^export\s+default\s+function\s+/gm, 'function ');

    // Replace dynamic import() calls with direct calls (all symbols are in scope
    // since all modules are inlined into the same IIFE).
    //
    // Three patterns exist in the source:
    //
    // 1. Multi-line block:  import('./mod.js').then(({ name }) => { ... });
    //    → Replace with a plain block: /* direct call (was import mod) */ { ... }
    //    Also must remove the closing `)` from the `});` that ends the .then() callback.
    //
    // 2. Single-expr destructure:  import('./mod.js').then(({ name }) => name(args));
    //    → Replace entire import().then(...) with just the call expression.
    //
    // 3. Single-expr namespace:  import('./mod.js').then(m => m.name())
    //    → Replace entire import().then(...) with just name().

    // Pass 1: Mark multi-line import blocks so we can fix their closing });
    const lines = code.split('\n');
    let openBlocks = 0;

    const fixedLines = lines.map(line => {
      // Pattern 1: multi-line — starts .then(({ name }) => {
      // Replace the import().then( portion with a block comment.
      // Track the block so we can fix the closing }); → }
      const blockMatch = line.match(/^(\s*)import\(['"]\.\/(\w+)\.js['"]\)\.then\(\s*\(\s*\{([^}]+)\}\s*\)\s*=>\s*\{(.*)$/);
      if (blockMatch) {
        const [, indent, mod, destructure, rest] = blockMatch;
        openBlocks++;
        return `${indent}/* direct call (was import ${mod}) */ {${rest}`;
      }

      // Pattern 3: .then(m => m.name()) — namespace access
      const nsMatch = line.match(/^(.*)import\(['"]\.\/(\w+)\.js['"]\)\.then\(\s*m\s*=>\s*m\.(\w+)\(\)\)(.*)$/);
      if (nsMatch) {
        const [, before, mod, func, after] = nsMatch;
        return `${before}${func}()${after}`;
      }

      // Pattern 2: .then(({ name }) => expr) on a single line
      // The expression after => may itself contain parens like toggleMarkdown(note)
      // or debouncedSave(), so we can't just count parens naively.
      // Strategy: find import('./...'), then .then(, then match the callback which
      // is ({...}) => <expr>). The <expr> extends to the closing ) of .then().
      // Since .then() always ends the statement on the same line (single-line pattern),
      // we find the LAST ) on the line that closes .then().
      const importStart = line.indexOf("import('./");
      if (importStart === -1) {
        const importStart2 = line.indexOf('import("./');
        if (importStart2 === -1) return line;
      }
      const idx = line.indexOf("import('./") !== -1 ? line.indexOf("import('./") : line.indexOf('import("./');
      const thenIdx = line.indexOf('.then(', idx);
      if (thenIdx === -1) return line;

      // Find the position right after .then(
      const thenOpenParen = thenIdx + 5; // index of '(' in '.then('

      // Find the matching closing ) for .then( by counting ALL bracket types
      let depth = 1; // we're inside .then(
      let endIdx = -1;
      for (let i = thenOpenParen + 1; i < line.length; i++) {
        const ch = line[i];
        if (ch === '(') depth++;
        else if (ch === ')') {
          depth--;
          if (depth === 0) {
            endIdx = i;
            break;
          }
        }
      }
      if (endIdx === -1) return line;

      // Extract the .then(...) content
      const thenContent = line.slice(thenOpenParen + 1, endIdx);

      // Try Pattern 2a: ({ name }) => expr
      const arrowMatch = thenContent.match(/^\s*\(\s*\{([^}]+)\}\s*\)\s*=>\s*([\s\S]+)$/);
      if (arrowMatch) {
        const [, destructure, expr] = arrowMatch;
        const before = line.slice(0, idx);
        const after = line.slice(endIdx + 1);
        return `${before}${expr.trim()}${after}`;
      }

      return line;
    });

    // Pass 2: Fix closing }); for Pattern 1 blocks
    // When we replaced import(...).then(({X}) => { with /* direct call */ {,
    // the corresponding closing }); still has the ) that closes .then().
    // We need to convert }); → }
    const finalLines = [];
    let blockDepth = 0;
    for (const line of fixedLines) {
      let newLine = line;
      if (line.includes('/* direct call (was import')) {
        blockDepth++;
      }
      if (blockDepth > 0) {
        // Match closing }); that is alone on a line (possibly with semicolon)
        const closingMatch = newLine.match(/^(\s*)\}\s*\);?\s*$/);
        if (closingMatch) {
          const indent = closingMatch[1];
          newLine = newLine.replace(/\}\s*\);?/, '}');
          blockDepth--;
        }
      }
      finalLines.push(newLine);
    }
    code = finalLines.join('\n');

    parts.push(`// =================== ${modName}.js ===================\n${code}\n\n`);
  }

  // Add the content.js entry point (after all modules are defined)
  let entryCode = fs.readFileSync(path.join(ROOT, 'content.js'), 'utf8');
  // Remove import lines
  entryCode = entryCode.replace(/^import\s+.*?;\s*$/gm, '');

  parts.push(`// =================== content.js (entry) ===================\n${entryCode}\n`);

  // Close IIFE
  parts.push(`\n})();\n`);

  // Compose the bundle
  const bundle = parts.join('\n');

  if (!fs.existsSync(TEMP_DIR)) {
    fs.mkdirSync(TEMP_DIR, { recursive: true });
  }

  fs.writeFileSync(path.join(TEMP_DIR, 'contentScript.js'), bundle);
  console.log('✅ Bundled contentScript.js created');

  // Verify the bundle doesn't have leftover import statements
  const leftoverImports = bundle.match(/^import\s/gm);
  if (leftoverImports) {
    console.warn(`⚠️  Warning: ${leftoverImports.length} import statement(s) remain in bundle`);
  }
}

function packageExtension() {
  console.log('\n📦 Packaging extension...\n');

  // Clean
  if (fs.existsSync(BUILD_DIR)) fs.rmSync(BUILD_DIR, { recursive: true });
  if (fs.existsSync(TEMP_DIR)) fs.rmSync(TEMP_DIR, { recursive: true });
  fs.mkdirSync(BUILD_DIR, { recursive: true });
  fs.mkdirSync(TEMP_DIR, { recursive: true });

  // Build the bundled content script first
  bundleContentScript();

  // Copy all necessary files
  const filesToCopy = ['background.js', 'styles.css'];
  for (const f of filesToCopy) {
    fs.copyFileSync(path.join(ROOT, f), path.join(TEMP_DIR, f));
  }

  // Copy icons directory
  fs.cpSync(path.join(ROOT, 'icons'), path.join(TEMP_DIR, 'icons'), { recursive: true });

  // Update manifest: point content_scripts to the bundled contentScript.js
  const manifest = JSON.parse(fs.readFileSync(path.join(ROOT, 'manifest.json'), 'utf8'));
  const version = manifest.version;
  
  const buildManifest = { ...manifest };
  buildManifest.content_scripts[0].js = ['contentScript.js'];
  fs.writeFileSync(path.join(TEMP_DIR, 'manifest.json'), JSON.stringify(buildManifest, null, 2));

  // Create zip using Python (always available) since 'zip' may not be installed
  const zipName = `sticky-notes-v${version}.zip`;
  const buildDir = path.join(ROOT, 'build');
  const zipPath = path.join(buildDir, zipName);
  
  // Python zip using absolute path (escape single quotes in path)
  const zipPathEsc = zipPath.replace(/'/g, "'\\''");
  const tempDirEsc = TEMP_DIR.replace(/'/g, "'\\''");
  
  try {
    execSync(`cd '${tempDirEsc}' && python3 -c "
import zipfile, os
with zipfile.ZipFile('${zipPathEsc}', 'w', zipfile.ZIP_DEFLATED) as zf:
    for root, dirs, files in os.walk('.'):
        for f in files:
            fp = os.path.join(root, f)
            zf.write(fp)
"`, { stdio: 'pipe' });
  } catch (e) {
    console.error('Failed to create zip with Python:', e.message);
    // Fallback: try zip command
    console.error('Trying zip command as fallback...');
    try {
      execSync(`cd '${tempDirEsc}' && zip -r '${zipPathEsc}' .`, { stdio: 'pipe' });
    } catch (e2) {
      console.error('Both zip methods failed. Cannot create package.');
      throw e2;
    }
  }

  // Clean up temp dir
  fs.rmSync(TEMP_DIR, { recursive: true });

  console.log(`\n✅ Build complete: ${BUILD_DIR}/${zipName}`);
  console.log(`   Version: ${version}`);
  
  // List build output
  const stats = fs.statSync(zipPath);
  console.log(`   Size: ${(stats.size / 1024).toFixed(1)} KB`);
}

// Run
try {
  packageExtension();
} catch (err) {
  console.error('❌ Build failed:', err.message);
  if (err.stack) console.error(err.stack);
  process.exit(1);
}